import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Daily Mental OS",
};

const SUPPORT_EMAIL = "myalongside@gmail.com";
const LAST_UPDATED = "July 1, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold text-white mb-3">{title}</h2>
      <div className="text-slate-300 leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link href="/" className="inline-flex items-center gap-2 text-slate-400 hover:text-white text-sm transition mb-10">
          <ArrowLeft size={16} />
          Back to home
        </Link>

        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-12">Last updated: {LAST_UPDATED}</p>

        <Section title="Not a medical service">
          <p>
            Daily Mental OS is an AI-powered coaching tool, not a licensed medical, psychiatric, or
            therapeutic service. The insights it generates are for informational and self-reflection purposes
            only and are not a diagnosis or treatment. It is not a substitute for professional mental health
            care. If you&apos;re experiencing a mental health emergency, contact emergency services or a crisis
            line (988 in the US) immediately — do not rely on this app.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            You&apos;re responsible for keeping your login credentials secure and for all activity under your
            account. You must be at least 18 years old (or the age of majority in your jurisdiction) to use
            Daily Mental OS.
          </p>
        </Section>

        <Section title="Plans & billing">
          <ul className="list-disc list-inside space-y-1">
            <li>Free: 3 AI check-ins per week, at no cost.</li>
            <li>Plus ($9.99/mo) and Pro ($14.99/mo): unlimited check-ins and additional features, billed monthly via Stripe.</li>
          </ul>
          <p>
            Subscriptions renew automatically each billing period until cancelled. You can cancel anytime from
            your account settings; you&apos;ll retain access through the end of the current billing period. We
            don&apos;t offer prorated refunds for partial periods.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>Use the service for anything unlawful or to harm others.</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the service or its AI systems.</li>
            <li>Share your account with others or resell access to the service.</li>
          </ul>
        </Section>

        <Section title="AI-generated content">
          <p>
            Coaching insights are generated by Anthropic&apos;s Claude models based on the check-in data you
            provide. Like any AI system, it can be wrong or miss context about your situation. Use your own
            judgment, and don&apos;t treat any insight as authoritative advice for a serious decision.
          </p>
        </Section>

        <Section title="Termination">
          <p>
            You may stop using Daily Mental OS and delete your account at any time. We may suspend or
            terminate accounts that violate these terms or that we reasonably believe pose a safety risk to
            the user or others.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            Daily Mental OS is provided &quot;as is,&quot; without warranties of any kind. To the fullest extent
            permitted by law, we are not liable for indirect, incidental, or consequential damages arising
            from your use of the service, including decisions made based on AI-generated insights.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p>
            We may update these terms from time to time. Continued use of the service after a change means
            you accept the updated terms.
          </p>
        </Section>

        <Section title="Contact us">
          <p>
            Questions about these terms? Reach out at{" "}
            <a href={`mailto:${SUPPORT_EMAIL}`} className="text-blue-400 hover:text-blue-300 underline">
              {SUPPORT_EMAIL}
            </a>.
          </p>
        </Section>
      </div>
    </div>
  );
}
